priv_key_file: "../../key" # Relative path from main.go, ideally use absolute path
http_port: 8080
log_level: "debug"
l1_rpc_url: "http://localhost:8545"
settlement_rpc_url: "http://localhost:8546"
l1_contract_addr: "0xB6CdBacC3737cC01b154BC7F8aFa1F2dc6c200b2"
settlement_contract_addr: "0x810E16Ded21b51b042F6F182887da861B5F53FA8"
pg_host: "localhost"
pg_port: 5432
pg_user: "user"
pg_password: "password"
pg_dbname: "dbname"
